services:
  wordpress:
    build:
      context: ./wordpress
    environment:
      - SERVICE_FQDN_WORDPRESS=${SERVICE_FQDN_WORDPRESS}
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
      # Optional: push a few constants straight into wp-config.php
      - WORDPRESS_CONFIG_EXTRA=define('WP_MEMORY_LIMIT','256M'); define('WP_MAX_MEMORY_LIMIT','256M');
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10
    volumes:
      - wordpress-files:/var/www/html
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$SERVICE_USER_WORDPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 20s
      retries: 10
